--- # Install Packages
- hosts: computers
  tasks:
  - name: Install deb packages from the internet
    apt:
      deb: "{{ item }}"
    vars:
    loop:
      - https://discordapp.com/api/download?platform=linux&format=deb
      - https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - https://downloads.slack-edge.com/linux_releases/slack-desktop-3.4.0-amd64.deb
      - https://go.microsoft.com/fwlink/?LinkID=760868
  - name: Update cache
    apt:
      update_cache: yes
      cache_valid_time: 86400
  become: yes
