--- # Install basic packages pretty much required for the system to function
- hosts: computers
  tasks:
  - name: Install Basic pacakges needed for the system to function
    apt:
      name: "{{ packages }}"
    vars:
        packages:
            - curl
            - git
            - tree
            - vim
            - gcc
            - build-essential
            - tree
  become: yes