--- # Install Packages
- hosts: computers
  tasks:
  - name: Install packages
    apt:
      name: "{{ packages }}"
    vars:
        packages:
          - steam
          - fonts-powerline
          - fonts-hack-ttf
          - arc-theme
          - chrome-gnome-shell
          - gnome-tweak-tool
          - adapta-gtk-theme
          - neofetch
          - streamlink
          - mpv
          - vlc
          - nautilus-dropbox
          - zsh
          - ulauncher
          - telegram-desktop
          - adapta-gtk-theme
          - papirus-icon-theme

  - name: Install communitheme, spotify snap
    command: snap install communitheme spotify
  become: true