# Install RPM Packages for fedora
- hosts: computers
  tasks:
  - name: Install Flatpaks for fedora
    flatpak:
      name: "{{ item }}"
      state: present
    with_items:
      - https://s3.amazonaws.com/alexlarsson/spotify-repo/spotify.flatpakref
      - https://flathub.org/repo/appstream/com.discordapp.Discord.flatpakref
      - https://flathub.org/repo/appstream/com.discordapp.Discord.flatpakref
