# Install FlatPaks for fedora.
- hosts: computers
  tasks:
  - name: Install Flatpaks for fedora
    flatpak:
      name: "{{ item }}"
      state: present
      method: user
    with_items:
      - https://flathub.org/repo/appstream/com.spotify.Client.flatpakref
      - https://flathub.org/repo/appstream/com.discordapp.Discord.flatpakref
      - https://flathub.org/repo/appstream/com.visualstudio.code.flatpakref
