--- # Set up RPM Fusion
- hosts: computers
  tasks:
  - name: Set up RPM Fusion on a Fedora system.
    dnf:
      name: "{{ item }}"
      state: present
    with_items:
      - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-30.noarch.rpm
      - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-30.noarch.rpm
    become: yes